{"name": "Восстановление пароля с валидным email", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/136.0.7103/chromedriver_win32.zip", "trace": "request = <SubRequest 'driver' for <Function test_navigate_to_restore_page>>\n\n    @pytest.fixture(scope=\"session\")\n    def driver(request):\n        browser = request.config.getoption(\"--browser\").lower()\n        headless = request.config.getoption(\"--headless\")\n        driver_instance = None  # Инициализация переменной\n    \n        try:\n            if browser == \"chrome\":\n                options = webdriver.ChromeOptions()\n                if headless:\n                    options.add_argument(\"--headless=new\")\n    \n                # Для стабильности фиксируем версию ChromeDriver\n                driver_instance = webdriver.Chrome(\n>                   service=ChromeService(ChromeDriverManager().install()),\n                    options=options\n                )\n\ntests\\conftest.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\webdriver_manager\\chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\download_manager.py:28: in download_file\n    response = self._http_client.get(url)\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/136.0.7103/chromedriver_win32.zip\n\nvenv\\Lib\\site-packages\\webdriver_manager\\core\\http.py:16: ValueError"}, "parameters": [{"name": "email", "value": "'test@example.com'"}], "start": 1747161850341, "stop": 1747161850341, "uuid": "fe7f3053-4d6e-47e7-9510-3ebdaae039dd", "historyId": "422bd85652c8f3ee78173852802f6fc3", "testCaseId": "cff131db8967b3557258e4bcef7072e3", "fullName": "tests.test_password_restore.TestPasswordRestore#test_password_restoration_with_valid_email", "labels": [{"name": "feature", "value": "Восстановление пароля"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_password_restore"}, {"name": "subSuite", "value": "TestPasswordRestore"}, {"name": "host", "value": "Gemini_78"}, {"name": "thread", "value": "8148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_password_restore"}]}